---
- name: Install Control Plane dependencies
  ansible.builtin.apt:
    name:
      - bash-completion
      - dnsutils
      - net-tools
      - jq
      - yq
    state: present
    update_cache: true
