- name: Read k3s node token from control-plane
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: token_output

- name: Save token locally
  copy:
    content: "{{ token_output.content | b64decode | trim }}"
    dest: "{{ playbook_dir }}/../artifacts/k3s_node_token.txt"
  delegate_to: localhost
  run_once: true
  become: false
