---
kub62:
  vars:
    ansible_ssh_private_key_file: "{{ lookup('env','HOME') }}/.ssh/id_d25519"
    ansible_uid: 1000
    ansible_user: pi
    clone_label_prefix: kub62
    locale: "de_AT.UTF-8"
    timezone: "Europe/Vienna"
  children:
    control_plane:
      hosts:
        kub62-control-plane:
          ansible_host: 192.168.10.10
          clone_destination: nvme
      vars:
        k3s_exec_flags: "--disable traefik --disable servicelb --disable local-storage --flannel-backend none --disable-network-policy"
    worker:
      hosts:
        kub62-worker-1:
          ansible_host: 192.168.10.11
          clone_destination: usb
        kub62-worker-2:
          ansible_host: 192.168.10.12
          clone_destination: nvme
    kiosk:
      hosts:
        kub62-kiosk-1:
          ansible_host: 192.168.10.13
          clone_destination: usb
          bodgestr_device_usb_id: "1234:5678"
      vars:
        kiosk_urls: "https://example.com/1 https://example.com/2"
