---
- name: Install Longhorn dependencies
  ansible.builtin.apt:
    name:
      - open-iscsi
      - nfs-common
      - smartmontools
      - cryptsetup
    state: present

- name: Load kernel modules Longhorn checks for
  community.general.modprobe:
    name: dm_crypt
    state: present
    persistent: present
