---
- name: Disable unnecessary features in config.txt
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    line: "{{ item }}"
    state: present
  loop:
    - dtoverlay=disable-bt
    - dtparam=act_led_trigger=none
    - dtparam=act_led_activelow=on
    - dtparam=audio=off
  register: disable_features
  become: true

- name: Mark reboot needed if any feature was disabled
  ansible.builtin.set_fact:
    reboot_needed: true
  when: disable_features.results | selectattr('changed') | list | length > 0

- name: Disable unnecessary services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - ModemManager
  become: true
  register: disable_services_result
  failed_when: false
  changed_when: disable_services_result is changed
