---
- name: Run rpi-eeprom-update
  ansible.builtin.command: rpi-eeprom-update -a
  become: true
  register: eeprom_update
  changed_when: '"bootloader update pending" in (eeprom_update.stdout | lower)'

- name: Mark reboot needed if EEPROM update applied # noqa: no-handler
  ansible.builtin.set_fact:
    reboot_needed: true
  when: eeprom_update.changed
