---
- name: Generate locale {{ locale }}
  community.general.locale_gen:
    name: "{{ locale }}"
    state: present

- name: Set locale variables
  ansible.builtin.lineinfile:
    path: /etc/default/locale
    regexp: "^{{ item }}="
    line: "{{ item }}={{ locale }}"
    create: true
    owner: root
    group: root
    mode: "0644"
  loop:
    - LANG
    - LC_ALL
