---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    autoclean: true
  register: apt_upgrade
  become: true

- name: Mark reboot needed if packages were upgraded # noqa: no-handler
  ansible.builtin.set_fact:
    reboot_needed: true
  when: apt_upgrade.changed
